environment: development
port: 4000

database:
  uri: mongodb://localhost:27017/twitter

jwt:
  secret-key: Ghsfdgdh2637JHFDHSJSKJSGSHBXVGFTSHUJIJS
  expiresin: 1

http:
  url: http://localhost:4000/

uploads:
  avatars: uploads/avatars/
  banners: uploads/banners/